version: '3.7'

services:
  nexusa:
    image: sonatype/nexus3
    container_name: nexusa
    ports:
      - "8090:8081"
    volumes:
      - nexus-data:/nexus-data
    networks:
      - my-network

  nginx:
    image: nginx
    container_name: nginx-reverse-proxy
    ports:
      - "8000:80"
    volumes:
      - ./nginx-config/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my-network
    depends_on:
      - nexusa

networks:
  my-network:
    driver: bridge

volumes:
  nexus-data: