version: '3.7'

services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root # Necessary for Docker socket access
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Mount the host's Docker socket
      - /usr/bin/docker:/usr/bin/docker
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
    networks:
      devops-network:
        ipv4_address: 172.26.0.3
  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
      - "8084:8084" 
    volumes:
      - nexus_data:/nexus-data
    networks:
      devops-network:
        ipv4_address: 172.26.0.2
  
  vault:
    image: hashicorp/vault
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_ADDR: http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
    networks:
      devops-network:
        ipv4_address: 172.26.0.4
    volumes:
      - vault_data:/vault/file

  nginx:
    image: nginx
    container_name: nginx-reverse-proxy
    ports:
      - "8000:80"
    volumes:
      - ./nginx-config/nginx.conf:/etc/nginx/nginx.conf
    networks:
      devops-network:
        ipv4_address: 172.26.0.5
      frontend_frontend:
    depends_on:
      - nexus
      - jenkins

networks:
  devops-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.26.0.0/16
  frontend_frontend:
    external: true

volumes:
  jenkins_data:
  nexus_data:
  vault_data:
