version: '3.8'
services:
  report-generator:
    # image: localhost:8084/report-generator:latest
    build: .
    ports:
      - "6069:8080"
    networks:
      - report-generator-inter
      - infrastructure_parcel-services
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_URI=http://service-discovery:8080/eureka/
networks:
  infrastructure_parcel-services:
    external: true
  report-generator-inter:
    external:
      name: infra-report-generator