version: '2'
services:
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password # at least 8 length
      - MINIO_DEFAULT_BUCKETS=test-bucket
  wiremock:
    image: "wiremock/wiremock:latest"
    container_name: wiremock
    ports:
      - '3080:8080'
    volumes:
      - ./src/main/resources/mocks:/home/wiremock/