version: '3.8'
services:
  frontend:
    image: localhost:8084/frontend:latest
    ports:
      - "3001:3000"
    networks:
      - infrastructure_edge-api

networks:
  infrastructure_edge-api:
    external: true

