version: '3.8'
services:
  api-gateway:
    image: localhost:8084/gateway:latest
    ports:
      - "7069:8080"
    networks:
      infrastructure_edge-api:
      infrastructure_parcel-services:
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_URI=http://service-discovery:8080/eureka/

networks:
  infrastructure_edge-api:
    external: true
  infrastructure_parcel-services:
    external: true
