version: '3.8'
services:
  api-gateway:
    image: localhost:8084/gateway:latest
    ports:
      - "7069:8080"
    networks:
      infrastructure_edge-api:
      infrastructure_parcel-services:

networks:
  infrastructure_edge-api:
    external: true
  infrastructure_parcel-services:
    external: true
