spring:
  application:
      name: report-generator
  cloud:
    config:
      discovery:
        enabled: true
        service-id: CONFIG-SERVER
    openfeign:
      client:
        config:
          parcel-finder:
  config:
    import: "optional:configserver:"
  minio:
    host: minio
    port: 9000
    username: minio-root-user
    password: minio-root-password

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://service-discovery:8080/eureka/}
  instance:
    preferIpAddress: true
logging:
  level:
    com.netflix.eureka: DEBUG
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - refresh