spring:
  minio:
    host: localhost
    port: 9000
    username: minio-root-user
    password: minio-root-password

  application:
    name: report-generator
  cloud:
    config:
      discovery:
        enabled: true
        service-id: CONFIG-SERVER
    openfeign:
      client:
        config:
          parcel-finder:
            url: http://localhost:6969
  config:
    import: "optional:configserver:"

server:
  port: 9999

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8080/eureka/}
  instance:
    preferIpAddress: true

logging:
  level:
    com.netflix.eureka: DEBUG
    com.parcel.reportgenerator.service: DEBUG

management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - '*'

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
    instances:
      reportGeneratorService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED