spring:
  application:
    name: service-discovery

eureka:
  instance:
    hostname: service-discovery
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8080/eureka/


