eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    com.netflix.discovery: 'OFF'
    com.netflix.com.netflix.eureka: 'OFF'


