version: '3.8'
services:
  config-server:
    image: localhost:8084/config-server:latest
    ports:
      - "7037:8080"
    networks:
      - infrastructure_parcel-services
    environment:
      - EUREKA_URI=http://service-discovery:8080/eureka/
networks:
  infrastructure_parcel-services:
    external: true
