spring:
  application:
    name: gateway

management:
  endpoints:
    web:
      exposure:
        include: info, health
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
