version: '3.8'
services:
  parcel-finder:
    build: .
    ports:
      - "7000:8080"
    networks:
      - parcel-finder-inter
      - infrastructure_parcel-services
networks:
  infrastructure_parcel-services:
    external: true
  parcel-finder-inter:
    external:
      name: infra-parcel-finder