spring:
  data:
    elasticsearch:
      cluster-nodes: elasticsearch:9200
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      bootstrap-servers: kafka:9092
  jpa:
    properties:
      hibernate:
        search:
          backend:
            hosts: elasticsearch:9200
hibernate:
  search:
    backend:
      hosts: elasticsearch:9200
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://service-discovery:8080/eureka}
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: refresh