spring:
  kafka:
    parcel-status-change-topic: parcel-status-change
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: localhost:29092
  application:
    name: parcel-tracker
  cloud:
    config:
      discovery:
        enabled: true
        service-id: CONFIG-SERVER
  config:
    import: "optional:configserver:"
  data:
    mongodb:
      uri: mongodb+srv://kuba:0CHAyP8alEibhumj@cluster.wnmcj.mongodb.net/?retryWrites=true&w=majority
      database: parceldb

server:
  port: 9090

logging:
  level:
    com:
      parcel:
        tracker: DEBUG

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#  instance:
#    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - info