spring:
  application:
    name: demo-app
  cloud:
    config:
      discovery:
        enabled: true
        service-id: CONFIG-SERVER
  config:
    import: "optional:configserver:"

server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: refresh